name: Claude Code Integration

on: [workflow_dispatch]

jobs:
  claude-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic  # Claude 官方 Python SDK

      - name: Run Claude Code Analysis
        run: |
          # 这里可以编写调用 Claude API 的脚本
          python .github/scripts/claude_analysis.py